// Patch application: `git apply`, falling back to a small unified-diff applier when git is
// unavailable or refuses the patch. Ported from tools/bench/run.py's `apply_patch()`.
//
// Every reference.patch is generated the same way (see bench/README.md, "Authoring a task"):
// `git diff --no-index a b` between two directories literally named `a` and `b`, so every path
// in the patch reads `a/a/<relpath>` and `b/b/<relpath>` -- git's own a/, b/ prefixes around the
// two directory names. Applying against a project copy's own root therefore strips 2 leading
// path components, not the usual 1. Patches under bench/tasks/ are generated by this project,
// not accepted from elsewhere, so the fallback does not need to be fuzzy: it trusts hunk context
// to match exactly.
export module mcppls.devtools.bench.patch;

import std;
import mcppls.base.error;

export namespace mcppls::devtools::bench {

inline constexpr int PATCH_STRIP_COMPONENTS { 2 };

// Applies `patchPath` (a unified diff with `a/a/...`, `b/b/...` paths) to `projectCopy`: tries
// `git apply` first, then the pure fallback below.
base::Result<void> apply_patch(const std::string& patchPath, const std::string& projectCopy);

// The fallback unified-diff applier alone (no git involved), exposed so its hunk/path handling
// can be exercised directly in tests without depending on git being on PATH.
base::Result<void> apply_unified_diff(std::string_view patchText, const std::string& root);

} // namespace mcppls::devtools::bench
