module mcppls.devtools.bench.patch;

import std;
import mcppls.base.error;
import mcppls.base.path;
import mcppls.base.text;
import mcppls.platform.env;
import mcppls.platform.fs;
import mcppls.platform.process;
import mcppls.platform.toolrun;

namespace mcppls::devtools::bench {
namespace {

namespace fs = mcppls::platform::fs;
namespace env = mcppls::platform::env;
namespace toolrun = mcppls::platform::toolrun;

// Splits `text` the way Python's `str.splitlines(keepends=True)` does for '\n'-terminated
// lines (every patch here is generated by `git diff`, which uses '\n'): each returned line
// keeps its trailing '\n', except a possible last line with none.
std::vector<std::string> split_keep_newline(std::string_view text) {
    std::vector<std::string> lines;
    std::size_t start { 0 };
    for (std::size_t i { 0 }; i < text.size(); ++i) {
        if (text[i] == '\n') {
            lines.emplace_back(text.substr(start, i - start + 1));
            start = i + 1;
        }
    }
    if (start < text.size()) lines.emplace_back(text.substr(start));
    return lines;
}

// The header line's path, with the `a/a/` or `b/b/` prefix (PATCH_STRIP_COMPONENTS levels)
// stripped, or nullopt for `/dev/null`. `headerRest` is everything after "--- "/"+++ ".
std::optional<std::string> diff_path(std::string_view headerRest) {
    const auto tab = headerRest.find('\t');
    std::string_view rest { tab == std::string_view::npos ? headerRest : headerRest.substr(0, tab) };
    rest = base::trim(rest);
    if (rest == "/dev/null") return std::nullopt;
    std::size_t skipped { 0 };
    std::string_view remainder { rest };
    for (int level { 0 }; level < PATCH_STRIP_COMPONENTS; ++level) {
        const auto slash = remainder.find('/');
        if (slash == std::string_view::npos) return std::string { rest };   // fewer than 2 components: keep as-is
        remainder = remainder.substr(slash + 1);
        ++skipped;
    }
    return std::string { remainder };
}

struct Hunk {
    int oldStart { 0 };
    std::vector<std::string> body;   // each line still tagged with its leading ' '/'-'/'+'
};

// `@@ -oldStart[,oldCount] +newStart[,newCount] @@`; only oldStart is used (matching run.py).
std::optional<int> parse_hunk_header(std::string_view line) {
    if (!line.starts_with("@@ -")) return std::nullopt;
    std::size_t i { 4 };
    std::size_t start { i };
    while (i < line.size() && std::isdigit(static_cast<unsigned char>(line[i]))) ++i;
    if (i == start) return std::nullopt;
    int value { 0 };
    for (std::size_t j { start }; j < i; ++j) value = value * 10 + (line[j] - '0');
    return value;
}

void apply_file_hunks(const std::string& root, const std::optional<std::string>& oldPath,
                      const std::optional<std::string>& newPath, const std::vector<Hunk>& hunks) {
    const std::optional<std::string>& targetRelOpt { newPath ? newPath : oldPath };
    if (!targetRelOpt) throw std::runtime_error { "a hunk names neither an old nor a new file" };
    const std::string targetRel { *targetRelOpt };

    std::vector<std::string> original;
    if (oldPath) {
        auto text = fs::read_file(base::join_path(root, *oldPath));
        if (!text) throw std::runtime_error { std::format("cannot read {}: {}", *oldPath, text.error().message) };
        original = split_keep_newline(*text);
    }

    std::vector<std::string> result;
    std::size_t cursor { 0 };
    for (const auto& hunk : hunks) {
        const std::size_t start0 { oldPath ? static_cast<std::size_t>(std::max(hunk.oldStart - 1, 0)) : std::size_t { 0 } };
        for (std::size_t i { cursor }; i < start0 && i < original.size(); ++i) result.push_back(original[i]);
        cursor = start0;
        for (const auto& hline : hunk.body) {
            const char tag { hline.empty() ? ' ' : hline.front() };
            const std::string content { hline.empty() ? std::string {} : hline.substr(1) };
            if (tag == ' ') {
                if (cursor >= original.size() || original[cursor] != content) {
                    throw std::runtime_error { std::format("context mismatch in {} at original line {}", targetRel, cursor + 1) };
                }
                result.push_back(content);
                ++cursor;
            } else if (tag == '-') {
                if (cursor >= original.size() || original[cursor] != content) {
                    throw std::runtime_error { std::format("deletion mismatch in {} at original line {}", targetRel, cursor + 1) };
                }
                ++cursor;
            } else if (tag == '+') {
                result.push_back(content);
            }
        }
    }
    for (std::size_t i { cursor }; i < original.size(); ++i) result.push_back(original[i]);

    const std::string target { base::join_path(root, targetRel) };
    if (!newPath) {
        if (fs::exists(target)) std::filesystem::remove(target);
        return;
    }
    if (auto created = fs::create_directories(base::parent_path(target)); !created) {
        throw std::runtime_error { std::format("cannot create {}: {}", base::parent_path(target), created.error().message) };
    }
    std::string joined;
    for (const auto& line : result) joined += line;
    if (auto written = fs::write_file(target, joined); !written) {
        throw std::runtime_error { std::format("cannot write {}: {}", target, written.error().message) };
    }
}

void apply_unified_diff_impl(std::string_view patchText, const std::string& root) {
    const auto lines = split_keep_newline(patchText);
    const std::size_t n { lines.size() };
    std::size_t i { 0 };
    while (i < n) {
        if (!lines[i].starts_with("--- ")) { ++i; continue; }
        const std::string oldHeader { lines[i] };
        ++i;
        if (i >= n || !lines[i].starts_with("+++ ")) {
            throw std::runtime_error { std::format("'+++' expected after '{}'", oldHeader) };
        }
        const std::string newHeader { lines[i] };
        ++i;
        const auto oldPath = diff_path(std::string_view { oldHeader }.substr(4));
        const auto newPath = diff_path(std::string_view { newHeader }.substr(4));

        std::vector<Hunk> hunks;
        while (i < n && lines[i].starts_with("@@")) {
            const auto oldStart = parse_hunk_header(lines[i]);
            if (!oldStart) throw std::runtime_error { std::format("malformed hunk header: '{}'", lines[i]) };
            ++i;
            Hunk hunk { .oldStart = *oldStart };
            while (i < n && !lines[i].empty() && (lines[i].front() == ' ' || lines[i].front() == '-' || lines[i].front() == '+')) {
                hunk.body.push_back(lines[i]);
                ++i;
                if (i < n && lines[i].starts_with("\\")) ++i;   // "\ No newline at end of file"
            }
            hunks.push_back(std::move(hunk));
        }
        apply_file_hunks(root, oldPath, newPath, hunks);
    }
}

} // namespace

base::Result<void> apply_unified_diff(std::string_view patchText, const std::string& root) {
    try {
        apply_unified_diff_impl(patchText, root);
        return {};
    } catch (const std::exception& error) {
        return base::fail("bench-patch", error.what());
    }
}

base::Result<void> apply_patch(const std::string& patchPath, const std::string& projectCopy) {
    std::string gitError;
    if (auto git = env::find_executable("git")) {
        // `--git-dir=/dev/null`: a project copy under `target/` sits inside THIS repository's
        // own work tree (there is nowhere else to put it that openkal's sandboxed file access
        // can reach -- see bench_validate.cpp). Plain `git apply`, run from a subdirectory of a
        // work tree, computes that subdirectory's "prefix" and silently "Skips" every hunk whose
        // (already `-p`-stripped) path does not itself start with that prefix -- every hunk here,
        // since the patch's paths are relative to the project root, not to the scratch directory
        // nested inside this repository. Detaching git from any repository at all (measured: a
        // patch that a real git repo silently skips end to end, an unrelated `git apply --stat`
        // outside any repository, and this exact flag) turns that prefix computation off, and the
        // patch applies exactly as it would in a directory with no enclosing repository.
        auto result = toolrun::run({
            .program = *git,
            // `core.autocrlf=false`: the Windows runner's system configuration sets it to true, so
            // git rewrote the patched lines with CRLF and the file no longer matched what the
            // patch says (test_bench_patch failed there alone). A patch's bytes are the answer.
            .arguments = { "-c", "core.autocrlf=false", "--git-dir=/dev/null", "apply", std::format("-p{}", PATCH_STRIP_COMPONENTS),
                           "--whitespace=nowarn", patchPath },
            .workDirectory = projectCopy,
            .purpose = "bench",
            .network = toolrun::Network::allowed,
            .bounds = mcppls::platform::RunBounds { .hard = std::chrono::seconds { 60 } },
        });
        if (result && result->exitCode == 0 && !result->timedOut) return {};
        if (result) gitError = base::trim(result->error);
    }
    auto text = mcppls::platform::fs::read_file(patchPath);
    if (!text) return std::unexpected { text.error() };
    auto fallback = apply_unified_diff(*text, projectCopy);
    if (fallback) return {};
    std::string detail { std::format("pure-diff patch apply: {}", fallback.error().message) };
    if (!gitError.empty()) detail = std::format("git apply: {}\n{}", gitError, detail);
    return base::fail("bench-patch", detail);
}

} // namespace mcppls::devtools::bench
