// Generated by mcppls-lspgen from the Language Server Protocol meta model 3.18.0.
// Do not edit: run `mcppls-lspgen generate` instead (tools/lspgen/README.md).
export module mcppls.lsp.protocol;

import std;

export namespace mcppls::lsp {

inline constexpr std::string_view PROTOCOL_VERSION { "3.18.0" };

enum class MessageDirection { client_to_server, server_to_client, both };

struct MethodInfo {
    std::string_view name;
    bool isRequest;
    MessageDirection direction;
    std::string_view clientCapability;   // dotted path in ClientCapabilities, or empty
    std::string_view serverCapability;   // dotted path in ServerCapabilities, or empty
};

// Every request and notification of the protocol, sorted by name.
std::span<const MethodInfo> methods();
const MethodInfo* find_method(std::string_view name);

} // namespace mcppls::lsp

export namespace mcppls::lsp::method {

inline constexpr std::string_view CANCEL_REQUEST { "$/cancelRequest" };
inline constexpr std::string_view LOG_TRACE { "$/logTrace" };
inline constexpr std::string_view PROGRESS { "$/progress" };
inline constexpr std::string_view SET_TRACE { "$/setTrace" };
inline constexpr std::string_view CALL_HIERARCHY_INCOMING_CALLS { "callHierarchy/incomingCalls" };
inline constexpr std::string_view CALL_HIERARCHY_OUTGOING_CALLS { "callHierarchy/outgoingCalls" };
inline constexpr std::string_view CLIENT_REGISTER_CAPABILITY { "client/registerCapability" };
inline constexpr std::string_view CLIENT_UNREGISTER_CAPABILITY { "client/unregisterCapability" };
inline constexpr std::string_view CODE_ACTION_RESOLVE { "codeAction/resolve" };
inline constexpr std::string_view CODE_LENS_RESOLVE { "codeLens/resolve" };
inline constexpr std::string_view COMPLETION_ITEM_RESOLVE { "completionItem/resolve" };
inline constexpr std::string_view DOCUMENT_LINK_RESOLVE { "documentLink/resolve" };
inline constexpr std::string_view EXIT { "exit" };
inline constexpr std::string_view INITIALIZE { "initialize" };
inline constexpr std::string_view INITIALIZED { "initialized" };
inline constexpr std::string_view INLAY_HINT_RESOLVE { "inlayHint/resolve" };
inline constexpr std::string_view NOTEBOOK_DOCUMENT_DID_CHANGE { "notebookDocument/didChange" };
inline constexpr std::string_view NOTEBOOK_DOCUMENT_DID_CLOSE { "notebookDocument/didClose" };
inline constexpr std::string_view NOTEBOOK_DOCUMENT_DID_OPEN { "notebookDocument/didOpen" };
inline constexpr std::string_view NOTEBOOK_DOCUMENT_DID_SAVE { "notebookDocument/didSave" };
inline constexpr std::string_view SHUTDOWN { "shutdown" };
inline constexpr std::string_view TELEMETRY_EVENT { "telemetry/event" };
inline constexpr std::string_view TEXT_DOCUMENT_CODE_ACTION { "textDocument/codeAction" };
inline constexpr std::string_view TEXT_DOCUMENT_CODE_LENS { "textDocument/codeLens" };
inline constexpr std::string_view TEXT_DOCUMENT_COLOR_PRESENTATION { "textDocument/colorPresentation" };
inline constexpr std::string_view TEXT_DOCUMENT_COMPLETION { "textDocument/completion" };
inline constexpr std::string_view TEXT_DOCUMENT_DECLARATION { "textDocument/declaration" };
inline constexpr std::string_view TEXT_DOCUMENT_DEFINITION { "textDocument/definition" };
inline constexpr std::string_view TEXT_DOCUMENT_DIAGNOSTIC { "textDocument/diagnostic" };
inline constexpr std::string_view TEXT_DOCUMENT_DID_CHANGE { "textDocument/didChange" };
inline constexpr std::string_view TEXT_DOCUMENT_DID_CLOSE { "textDocument/didClose" };
inline constexpr std::string_view TEXT_DOCUMENT_DID_OPEN { "textDocument/didOpen" };
inline constexpr std::string_view TEXT_DOCUMENT_DID_SAVE { "textDocument/didSave" };
inline constexpr std::string_view TEXT_DOCUMENT_DOCUMENT_COLOR { "textDocument/documentColor" };
inline constexpr std::string_view TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT { "textDocument/documentHighlight" };
inline constexpr std::string_view TEXT_DOCUMENT_DOCUMENT_LINK { "textDocument/documentLink" };
inline constexpr std::string_view TEXT_DOCUMENT_DOCUMENT_SYMBOL { "textDocument/documentSymbol" };
inline constexpr std::string_view TEXT_DOCUMENT_FOLDING_RANGE { "textDocument/foldingRange" };
inline constexpr std::string_view TEXT_DOCUMENT_FORMATTING { "textDocument/formatting" };
inline constexpr std::string_view TEXT_DOCUMENT_HOVER { "textDocument/hover" };
inline constexpr std::string_view TEXT_DOCUMENT_IMPLEMENTATION { "textDocument/implementation" };
inline constexpr std::string_view TEXT_DOCUMENT_INLAY_HINT { "textDocument/inlayHint" };
inline constexpr std::string_view TEXT_DOCUMENT_INLINE_COMPLETION { "textDocument/inlineCompletion" };
inline constexpr std::string_view TEXT_DOCUMENT_INLINE_VALUE { "textDocument/inlineValue" };
inline constexpr std::string_view TEXT_DOCUMENT_LINKED_EDITING_RANGE { "textDocument/linkedEditingRange" };
inline constexpr std::string_view TEXT_DOCUMENT_MONIKER { "textDocument/moniker" };
inline constexpr std::string_view TEXT_DOCUMENT_ON_TYPE_FORMATTING { "textDocument/onTypeFormatting" };
inline constexpr std::string_view TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY { "textDocument/prepareCallHierarchy" };
inline constexpr std::string_view TEXT_DOCUMENT_PREPARE_RENAME { "textDocument/prepareRename" };
inline constexpr std::string_view TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY { "textDocument/prepareTypeHierarchy" };
inline constexpr std::string_view TEXT_DOCUMENT_PUBLISH_DIAGNOSTICS { "textDocument/publishDiagnostics" };
inline constexpr std::string_view TEXT_DOCUMENT_RANGE_FORMATTING { "textDocument/rangeFormatting" };
inline constexpr std::string_view TEXT_DOCUMENT_RANGES_FORMATTING { "textDocument/rangesFormatting" };
inline constexpr std::string_view TEXT_DOCUMENT_REFERENCES { "textDocument/references" };
inline constexpr std::string_view TEXT_DOCUMENT_RENAME { "textDocument/rename" };
inline constexpr std::string_view TEXT_DOCUMENT_SELECTION_RANGE { "textDocument/selectionRange" };
inline constexpr std::string_view TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL { "textDocument/semanticTokens/full" };
inline constexpr std::string_view TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA { "textDocument/semanticTokens/full/delta" };
inline constexpr std::string_view TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE { "textDocument/semanticTokens/range" };
inline constexpr std::string_view TEXT_DOCUMENT_SIGNATURE_HELP { "textDocument/signatureHelp" };
inline constexpr std::string_view TEXT_DOCUMENT_TYPE_DEFINITION { "textDocument/typeDefinition" };
inline constexpr std::string_view TEXT_DOCUMENT_WILL_SAVE { "textDocument/willSave" };
inline constexpr std::string_view TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL { "textDocument/willSaveWaitUntil" };
inline constexpr std::string_view TYPE_HIERARCHY_SUBTYPES { "typeHierarchy/subtypes" };
inline constexpr std::string_view TYPE_HIERARCHY_SUPERTYPES { "typeHierarchy/supertypes" };
inline constexpr std::string_view WINDOW_LOG_MESSAGE { "window/logMessage" };
inline constexpr std::string_view WINDOW_SHOW_DOCUMENT { "window/showDocument" };
inline constexpr std::string_view WINDOW_SHOW_MESSAGE { "window/showMessage" };
inline constexpr std::string_view WINDOW_SHOW_MESSAGE_REQUEST { "window/showMessageRequest" };
inline constexpr std::string_view WINDOW_WORK_DONE_PROGRESS_CANCEL { "window/workDoneProgress/cancel" };
inline constexpr std::string_view WINDOW_WORK_DONE_PROGRESS_CREATE { "window/workDoneProgress/create" };
inline constexpr std::string_view WORKSPACE_APPLY_EDIT { "workspace/applyEdit" };
inline constexpr std::string_view WORKSPACE_CODE_LENS_REFRESH { "workspace/codeLens/refresh" };
inline constexpr std::string_view WORKSPACE_CONFIGURATION { "workspace/configuration" };
inline constexpr std::string_view WORKSPACE_DIAGNOSTIC { "workspace/diagnostic" };
inline constexpr std::string_view WORKSPACE_DIAGNOSTIC_REFRESH { "workspace/diagnostic/refresh" };
inline constexpr std::string_view WORKSPACE_DID_CHANGE_CONFIGURATION { "workspace/didChangeConfiguration" };
inline constexpr std::string_view WORKSPACE_DID_CHANGE_WATCHED_FILES { "workspace/didChangeWatchedFiles" };
inline constexpr std::string_view WORKSPACE_DID_CHANGE_WORKSPACE_FOLDERS { "workspace/didChangeWorkspaceFolders" };
inline constexpr std::string_view WORKSPACE_DID_CREATE_FILES { "workspace/didCreateFiles" };
inline constexpr std::string_view WORKSPACE_DID_DELETE_FILES { "workspace/didDeleteFiles" };
inline constexpr std::string_view WORKSPACE_DID_RENAME_FILES { "workspace/didRenameFiles" };
inline constexpr std::string_view WORKSPACE_EXECUTE_COMMAND { "workspace/executeCommand" };
inline constexpr std::string_view WORKSPACE_FOLDING_RANGE_REFRESH { "workspace/foldingRange/refresh" };
inline constexpr std::string_view WORKSPACE_INLAY_HINT_REFRESH { "workspace/inlayHint/refresh" };
inline constexpr std::string_view WORKSPACE_INLINE_VALUE_REFRESH { "workspace/inlineValue/refresh" };
inline constexpr std::string_view WORKSPACE_SEMANTIC_TOKENS_REFRESH { "workspace/semanticTokens/refresh" };
inline constexpr std::string_view WORKSPACE_SYMBOL { "workspace/symbol" };
inline constexpr std::string_view WORKSPACE_TEXT_DOCUMENT_CONTENT { "workspace/textDocumentContent" };
inline constexpr std::string_view WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH { "workspace/textDocumentContent/refresh" };
inline constexpr std::string_view WORKSPACE_WILL_CREATE_FILES { "workspace/willCreateFiles" };
inline constexpr std::string_view WORKSPACE_WILL_DELETE_FILES { "workspace/willDeleteFiles" };
inline constexpr std::string_view WORKSPACE_WILL_RENAME_FILES { "workspace/willRenameFiles" };
inline constexpr std::string_view WORKSPACE_WORKSPACE_FOLDERS { "workspace/workspaceFolders" };
inline constexpr std::string_view WORKSPACE_SYMBOL_RESOLVE { "workspaceSymbol/resolve" };

} // namespace mcppls::lsp::method

export namespace mcppls::lsp {

namespace semantic_token_types {
inline constexpr std::string_view NAMESPACE { "namespace" };
inline constexpr std::string_view TYPE { "type" };
inline constexpr std::string_view CLASS { "class" };
inline constexpr std::string_view ENUM { "enum" };
inline constexpr std::string_view INTERFACE { "interface" };
inline constexpr std::string_view STRUCT { "struct" };
inline constexpr std::string_view TYPE_PARAMETER { "typeParameter" };
inline constexpr std::string_view PARAMETER { "parameter" };
inline constexpr std::string_view VARIABLE { "variable" };
inline constexpr std::string_view PROPERTY { "property" };
inline constexpr std::string_view ENUM_MEMBER { "enumMember" };
inline constexpr std::string_view EVENT { "event" };
inline constexpr std::string_view FUNCTION { "function" };
inline constexpr std::string_view METHOD { "method" };
inline constexpr std::string_view MACRO { "macro" };
inline constexpr std::string_view KEYWORD { "keyword" };
inline constexpr std::string_view MODIFIER { "modifier" };
inline constexpr std::string_view COMMENT { "comment" };
inline constexpr std::string_view STRING { "string" };
inline constexpr std::string_view NUMBER { "number" };
inline constexpr std::string_view REGEXP { "regexp" };
inline constexpr std::string_view OPERATOR { "operator" };
inline constexpr std::string_view DECORATOR { "decorator" };
inline constexpr std::string_view LABEL { "label" };
} // namespace semantic_token_types

namespace semantic_token_modifiers {
inline constexpr std::string_view DECLARATION { "declaration" };
inline constexpr std::string_view DEFINITION { "definition" };
inline constexpr std::string_view READONLY { "readonly" };
inline constexpr std::string_view STATIC { "static" };
inline constexpr std::string_view DEPRECATED { "deprecated" };
inline constexpr std::string_view ABSTRACT { "abstract" };
inline constexpr std::string_view ASYNC { "async" };
inline constexpr std::string_view MODIFICATION { "modification" };
inline constexpr std::string_view DOCUMENTATION { "documentation" };
inline constexpr std::string_view DEFAULT_LIBRARY { "defaultLibrary" };
} // namespace semantic_token_modifiers

namespace document_diagnostic_report_kind {
inline constexpr std::string_view FULL { "full" };
inline constexpr std::string_view UNCHANGED { "unchanged" };
} // namespace document_diagnostic_report_kind

enum class ErrorCodes : std::int32_t {
    parse_error = -32700,
    invalid_request = -32600,
    method_not_found = -32601,
    invalid_params = -32602,
    internal_error = -32603,
    server_not_initialized = -32002,
    unknown_error_code = -32001,
};

enum class LSPErrorCodes : std::int32_t {
    request_failed = -32803,
    server_cancelled = -32802,
    content_modified = -32801,
    request_cancelled = -32800,
};

namespace folding_range_kind {
inline constexpr std::string_view COMMENT { "comment" };
inline constexpr std::string_view IMPORTS { "imports" };
inline constexpr std::string_view REGION { "region" };
} // namespace folding_range_kind

enum class SymbolKind : std::uint32_t {
    file = 1,
    module_ = 2,
    namespace_ = 3,
    package = 4,
    class_ = 5,
    method = 6,
    property = 7,
    field = 8,
    constructor = 9,
    enum_ = 10,
    interface = 11,
    function = 12,
    variable = 13,
    constant = 14,
    string = 15,
    number = 16,
    boolean = 17,
    array = 18,
    object = 19,
    key = 20,
    null = 21,
    enum_member = 22,
    struct_ = 23,
    event = 24,
    operator_ = 25,
    type_parameter = 26,
};

enum class SymbolTag : std::uint32_t {
    deprecated = 1,
};

namespace uniqueness_level {
inline constexpr std::string_view DOCUMENT { "document" };
inline constexpr std::string_view PROJECT { "project" };
inline constexpr std::string_view GROUP { "group" };
inline constexpr std::string_view SCHEME { "scheme" };
inline constexpr std::string_view GLOBAL { "global" };
} // namespace uniqueness_level

namespace moniker_kind {
inline constexpr std::string_view IMPORT { "import" };
inline constexpr std::string_view EXPORT { "export" };
inline constexpr std::string_view LOCAL { "local" };
} // namespace moniker_kind

enum class InlayHintKind : std::uint32_t {
    type = 1,
    parameter = 2,
};

enum class MessageType : std::uint32_t {
    error = 1,
    warning = 2,
    info = 3,
    log = 4,
    debug = 5,
};

enum class TextDocumentSyncKind : std::uint32_t {
    none = 0,
    full = 1,
    incremental = 2,
};

enum class TextDocumentSaveReason : std::uint32_t {
    manual = 1,
    after_delay = 2,
    focus_out = 3,
};

enum class CompletionItemKind : std::uint32_t {
    text = 1,
    method = 2,
    function = 3,
    constructor = 4,
    field = 5,
    variable = 6,
    class_ = 7,
    interface = 8,
    module_ = 9,
    property = 10,
    unit = 11,
    value = 12,
    enum_ = 13,
    keyword = 14,
    snippet = 15,
    color = 16,
    file = 17,
    reference = 18,
    folder = 19,
    enum_member = 20,
    constant = 21,
    struct_ = 22,
    event = 23,
    operator_ = 24,
    type_parameter = 25,
};

enum class CompletionItemTag : std::uint32_t {
    deprecated = 1,
};

enum class InsertTextFormat : std::uint32_t {
    plain_text = 1,
    snippet = 2,
};

enum class InsertTextMode : std::uint32_t {
    as_is = 1,
    adjust_indentation = 2,
};

enum class DocumentHighlightKind : std::uint32_t {
    text = 1,
    read = 2,
    write = 3,
};

namespace code_action_kind {
inline constexpr std::string_view EMPTY { "" };
inline constexpr std::string_view QUICK_FIX { "quickfix" };
inline constexpr std::string_view REFACTOR { "refactor" };
inline constexpr std::string_view REFACTOR_EXTRACT { "refactor.extract" };
inline constexpr std::string_view REFACTOR_INLINE { "refactor.inline" };
inline constexpr std::string_view REFACTOR_MOVE { "refactor.move" };
inline constexpr std::string_view REFACTOR_REWRITE { "refactor.rewrite" };
inline constexpr std::string_view SOURCE { "source" };
inline constexpr std::string_view SOURCE_ORGANIZE_IMPORTS { "source.organizeImports" };
inline constexpr std::string_view SOURCE_FIX_ALL { "source.fixAll" };
inline constexpr std::string_view NOTEBOOK { "notebook" };
} // namespace code_action_kind

enum class CodeActionTag : std::uint32_t {
    llm_generated = 1,
};

namespace trace_value {
inline constexpr std::string_view OFF { "off" };
inline constexpr std::string_view MESSAGES { "messages" };
inline constexpr std::string_view VERBOSE { "verbose" };
} // namespace trace_value

namespace markup_kind {
inline constexpr std::string_view PLAIN_TEXT { "plaintext" };
inline constexpr std::string_view MARKDOWN { "markdown" };
} // namespace markup_kind

namespace language_kind {
inline constexpr std::string_view ABAP { "abap" };
inline constexpr std::string_view WINDOWS_BAT { "bat" };
inline constexpr std::string_view BIB_TE_X { "bibtex" };
inline constexpr std::string_view CLOJURE { "clojure" };
inline constexpr std::string_view COFFEESCRIPT { "coffeescript" };
inline constexpr std::string_view C { "c" };
inline constexpr std::string_view CPP { "cpp" };
inline constexpr std::string_view C_SHARP { "csharp" };
inline constexpr std::string_view CSS { "css" };
inline constexpr std::string_view D { "d" };
inline constexpr std::string_view DELPHI { "pascal" };
inline constexpr std::string_view DIFF { "diff" };
inline constexpr std::string_view DART { "dart" };
inline constexpr std::string_view DOCKERFILE { "dockerfile" };
inline constexpr std::string_view ELIXIR { "elixir" };
inline constexpr std::string_view ERLANG { "erlang" };
inline constexpr std::string_view F_SHARP { "fsharp" };
inline constexpr std::string_view GIT_COMMIT { "git-commit" };
inline constexpr std::string_view GIT_REBASE { "git-rebase" };
inline constexpr std::string_view GO { "go" };
inline constexpr std::string_view GROOVY { "groovy" };
inline constexpr std::string_view HANDLEBARS { "handlebars" };
inline constexpr std::string_view HASKELL { "haskell" };
inline constexpr std::string_view HTML { "html" };
inline constexpr std::string_view INI { "ini" };
inline constexpr std::string_view JAVA { "java" };
inline constexpr std::string_view JAVA_SCRIPT { "javascript" };
inline constexpr std::string_view JAVA_SCRIPT_REACT { "javascriptreact" };
inline constexpr std::string_view JSON { "json" };
inline constexpr std::string_view LA_TE_X { "latex" };
inline constexpr std::string_view LESS { "less" };
inline constexpr std::string_view LUA { "lua" };
inline constexpr std::string_view MAKEFILE { "makefile" };
inline constexpr std::string_view MARKDOWN { "markdown" };
inline constexpr std::string_view OBJECTIVE_C { "objective-c" };
inline constexpr std::string_view OBJECTIVE_CPP { "objective-cpp" };
inline constexpr std::string_view PASCAL { "pascal" };
inline constexpr std::string_view PERL { "perl" };
inline constexpr std::string_view PERL6 { "perl6" };
inline constexpr std::string_view PHP { "php" };
inline constexpr std::string_view PLAINTEXT { "plaintext" };
inline constexpr std::string_view POWERSHELL { "powershell" };
inline constexpr std::string_view PUG { "jade" };
inline constexpr std::string_view PYTHON { "python" };
inline constexpr std::string_view R { "r" };
inline constexpr std::string_view RAZOR { "razor" };
inline constexpr std::string_view RUBY { "ruby" };
inline constexpr std::string_view RUST { "rust" };
inline constexpr std::string_view SCSS { "scss" };
inline constexpr std::string_view SASS { "sass" };
inline constexpr std::string_view SCALA { "scala" };
inline constexpr std::string_view SHADER_LAB { "shaderlab" };
inline constexpr std::string_view SHELL_SCRIPT { "shellscript" };
inline constexpr std::string_view SQL { "sql" };
inline constexpr std::string_view SWIFT { "swift" };
inline constexpr std::string_view TYPE_SCRIPT { "typescript" };
inline constexpr std::string_view TYPE_SCRIPT_REACT { "typescriptreact" };
inline constexpr std::string_view TE_X { "tex" };
inline constexpr std::string_view VISUAL_BASIC { "vb" };
inline constexpr std::string_view XML { "xml" };
inline constexpr std::string_view XSL { "xsl" };
inline constexpr std::string_view YAML { "yaml" };
} // namespace language_kind

enum class InlineCompletionTriggerKind : std::uint32_t {
    invoked = 1,
    automatic = 2,
};

namespace position_encoding_kind {
inline constexpr std::string_view UTF8 { "utf-8" };
inline constexpr std::string_view UTF16 { "utf-16" };
inline constexpr std::string_view UTF32 { "utf-32" };
} // namespace position_encoding_kind

enum class FileChangeType : std::uint32_t {
    created = 1,
    changed = 2,
    deleted = 3,
};

enum class WatchKind : std::uint32_t {
    create = 1,
    change = 2,
    delete_ = 4,
};

enum class DiagnosticSeverity : std::uint32_t {
    error = 1,
    warning = 2,
    information = 3,
    hint = 4,
};

enum class DiagnosticTag : std::uint32_t {
    unnecessary = 1,
    deprecated = 2,
};

enum class CompletionTriggerKind : std::uint32_t {
    invoked = 1,
    trigger_character = 2,
    trigger_for_incomplete_completions = 3,
};

enum class ApplyKind : std::uint32_t {
    replace = 1,
    merge = 2,
};

enum class SignatureHelpTriggerKind : std::uint32_t {
    invoked = 1,
    trigger_character = 2,
    content_change = 3,
};

enum class CodeActionTriggerKind : std::uint32_t {
    invoked = 1,
    automatic = 2,
};

namespace file_operation_pattern_kind {
inline constexpr std::string_view FILE { "file" };
inline constexpr std::string_view FOLDER { "folder" };
} // namespace file_operation_pattern_kind

enum class NotebookCellKind : std::uint32_t {
    markup = 1,
    code = 2,
};

namespace resource_operation_kind {
inline constexpr std::string_view CREATE { "create" };
inline constexpr std::string_view RENAME { "rename" };
inline constexpr std::string_view DELETE { "delete" };
} // namespace resource_operation_kind

namespace failure_handling_kind {
inline constexpr std::string_view ABORT { "abort" };
inline constexpr std::string_view TRANSACTIONAL { "transactional" };
inline constexpr std::string_view TEXT_ONLY_TRANSACTIONAL { "textOnlyTransactional" };
inline constexpr std::string_view UNDO { "undo" };
} // namespace failure_handling_kind

enum class PrepareSupportDefaultBehavior : std::uint32_t {
    identifier = 1,
};

namespace token_format {
inline constexpr std::string_view RELATIVE { "relative" };
} // namespace token_format

} // namespace mcppls::lsp
