// Generated by mcppls-lspgen from the Language Server Protocol meta model 3.18.0.
// Do not edit: run `mcppls-lspgen generate` instead (tools/lspgen/README.md).
module mcppls.lsp.protocol;

import std;

namespace mcppls::lsp {

namespace {

constexpr std::array<MethodInfo, 95> METHODS { {
    MethodInfo { "$/cancelRequest", false, MessageDirection::both, "", "" },
    MethodInfo { "$/logTrace", false, MessageDirection::server_to_client, "", "" },
    MethodInfo { "$/progress", false, MessageDirection::both, "", "" },
    MethodInfo { "$/setTrace", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "callHierarchy/incomingCalls", true, MessageDirection::client_to_server, "textDocument.callHierarchy", "callHierarchyProvider" },
    MethodInfo { "callHierarchy/outgoingCalls", true, MessageDirection::client_to_server, "textDocument.callHierarchy", "callHierarchyProvider" },
    MethodInfo { "client/registerCapability", true, MessageDirection::server_to_client, "", "" },
    MethodInfo { "client/unregisterCapability", true, MessageDirection::server_to_client, "", "" },
    MethodInfo { "codeAction/resolve", true, MessageDirection::client_to_server, "textDocument.codeAction.resolveSupport", "codeActionProvider.resolveProvider" },
    MethodInfo { "codeLens/resolve", true, MessageDirection::client_to_server, "textDocument.codeLens.resolveSupport", "codeLensProvider.resolveProvider" },
    MethodInfo { "completionItem/resolve", true, MessageDirection::client_to_server, "textDocument.completion.completionItem.resolveSupport", "completionProvider.resolveProvider" },
    MethodInfo { "documentLink/resolve", true, MessageDirection::client_to_server, "textDocument.documentLink", "documentLinkProvider.resolveProvider" },
    MethodInfo { "exit", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "initialize", true, MessageDirection::client_to_server, "", "" },
    MethodInfo { "initialized", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "inlayHint/resolve", true, MessageDirection::client_to_server, "textDocument.inlayHint.resolveSupport", "inlayHintProvider.resolveProvider" },
    MethodInfo { "notebookDocument/didChange", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "notebookDocument/didClose", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "notebookDocument/didOpen", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "notebookDocument/didSave", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "shutdown", true, MessageDirection::client_to_server, "", "" },
    MethodInfo { "telemetry/event", false, MessageDirection::server_to_client, "", "" },
    MethodInfo { "textDocument/codeAction", true, MessageDirection::client_to_server, "textDocument.codeAction", "codeActionProvider" },
    MethodInfo { "textDocument/codeLens", true, MessageDirection::client_to_server, "textDocument.codeLens", "codeLensProvider" },
    MethodInfo { "textDocument/colorPresentation", true, MessageDirection::client_to_server, "textDocument.colorProvider", "colorProvider" },
    MethodInfo { "textDocument/completion", true, MessageDirection::client_to_server, "textDocument.completion", "completionProvider" },
    MethodInfo { "textDocument/declaration", true, MessageDirection::client_to_server, "textDocument.declaration", "declarationProvider" },
    MethodInfo { "textDocument/definition", true, MessageDirection::client_to_server, "textDocument.definition", "definitionProvider" },
    MethodInfo { "textDocument/diagnostic", true, MessageDirection::client_to_server, "textDocument.diagnostic", "diagnosticProvider" },
    MethodInfo { "textDocument/didChange", false, MessageDirection::client_to_server, "textDocument.synchronization", "textDocumentSync" },
    MethodInfo { "textDocument/didClose", false, MessageDirection::client_to_server, "textDocument.synchronization", "textDocumentSync.openClose" },
    MethodInfo { "textDocument/didOpen", false, MessageDirection::client_to_server, "textDocument.synchronization", "textDocumentSync.openClose" },
    MethodInfo { "textDocument/didSave", false, MessageDirection::client_to_server, "textDocument.synchronization.didSave", "textDocumentSync.save" },
    MethodInfo { "textDocument/documentColor", true, MessageDirection::client_to_server, "textDocument.colorProvider", "colorProvider" },
    MethodInfo { "textDocument/documentHighlight", true, MessageDirection::client_to_server, "textDocument.documentHighlight", "documentHighlightProvider" },
    MethodInfo { "textDocument/documentLink", true, MessageDirection::client_to_server, "textDocument.documentLink", "documentLinkProvider" },
    MethodInfo { "textDocument/documentSymbol", true, MessageDirection::client_to_server, "textDocument.documentSymbol", "documentSymbolProvider" },
    MethodInfo { "textDocument/foldingRange", true, MessageDirection::client_to_server, "textDocument.foldingRange", "foldingRangeProvider" },
    MethodInfo { "textDocument/formatting", true, MessageDirection::client_to_server, "textDocument.formatting", "documentFormattingProvider" },
    MethodInfo { "textDocument/hover", true, MessageDirection::client_to_server, "textDocument.hover", "hoverProvider" },
    MethodInfo { "textDocument/implementation", true, MessageDirection::client_to_server, "textDocument.implementation", "implementationProvider" },
    MethodInfo { "textDocument/inlayHint", true, MessageDirection::client_to_server, "textDocument.inlayHint", "inlayHintProvider" },
    MethodInfo { "textDocument/inlineCompletion", true, MessageDirection::client_to_server, "textDocument.inlineCompletion", "inlineCompletionProvider" },
    MethodInfo { "textDocument/inlineValue", true, MessageDirection::client_to_server, "textDocument.inlineValue", "inlineValueProvider" },
    MethodInfo { "textDocument/linkedEditingRange", true, MessageDirection::client_to_server, "textDocument.linkedEditingRange", "linkedEditingRangeProvider" },
    MethodInfo { "textDocument/moniker", true, MessageDirection::client_to_server, "textDocument.moniker", "monikerProvider" },
    MethodInfo { "textDocument/onTypeFormatting", true, MessageDirection::client_to_server, "textDocument.onTypeFormatting", "documentOnTypeFormattingProvider" },
    MethodInfo { "textDocument/prepareCallHierarchy", true, MessageDirection::client_to_server, "textDocument.callHierarchy", "callHierarchyProvider" },
    MethodInfo { "textDocument/prepareRename", true, MessageDirection::client_to_server, "textDocument.rename.prepareSupport", "renameProvider.prepareProvider" },
    MethodInfo { "textDocument/prepareTypeHierarchy", true, MessageDirection::client_to_server, "textDocument.typeHierarchy", "typeHierarchyProvider" },
    MethodInfo { "textDocument/publishDiagnostics", false, MessageDirection::server_to_client, "textDocument.publishDiagnostics", "" },
    MethodInfo { "textDocument/rangeFormatting", true, MessageDirection::client_to_server, "textDocument.rangeFormatting", "documentRangeFormattingProvider" },
    MethodInfo { "textDocument/rangesFormatting", true, MessageDirection::client_to_server, "textDocument.rangeFormatting.rangesSupport", "documentRangeFormattingProvider.rangesSupport" },
    MethodInfo { "textDocument/references", true, MessageDirection::client_to_server, "textDocument.references", "referencesProvider" },
    MethodInfo { "textDocument/rename", true, MessageDirection::client_to_server, "textDocument.rename", "renameProvider" },
    MethodInfo { "textDocument/selectionRange", true, MessageDirection::client_to_server, "textDocument.selectionRange", "selectionRangeProvider" },
    MethodInfo { "textDocument/semanticTokens/full", true, MessageDirection::client_to_server, "textDocument.semanticTokens", "semanticTokensProvider" },
    MethodInfo { "textDocument/semanticTokens/full/delta", true, MessageDirection::client_to_server, "textDocument.semanticTokens.requests.full.delta", "semanticTokensProvider.full.delta" },
    MethodInfo { "textDocument/semanticTokens/range", true, MessageDirection::client_to_server, "textDocument.semanticTokens.requests.range", "semanticTokensProvider.range" },
    MethodInfo { "textDocument/signatureHelp", true, MessageDirection::client_to_server, "textDocument.signatureHelp", "signatureHelpProvider" },
    MethodInfo { "textDocument/typeDefinition", true, MessageDirection::client_to_server, "textDocument.typeDefinition", "typeDefinitionProvider" },
    MethodInfo { "textDocument/willSave", false, MessageDirection::client_to_server, "textDocument.synchronization.willSave", "textDocumentSync.willSave" },
    MethodInfo { "textDocument/willSaveWaitUntil", true, MessageDirection::client_to_server, "textDocument.synchronization.willSaveWaitUntil", "textDocumentSync.willSaveWaitUntil" },
    MethodInfo { "typeHierarchy/subtypes", true, MessageDirection::client_to_server, "", "" },
    MethodInfo { "typeHierarchy/supertypes", true, MessageDirection::client_to_server, "", "" },
    MethodInfo { "window/logMessage", false, MessageDirection::server_to_client, "", "" },
    MethodInfo { "window/showDocument", true, MessageDirection::server_to_client, "window.showDocument.support", "" },
    MethodInfo { "window/showMessage", false, MessageDirection::server_to_client, "window.showMessage", "" },
    MethodInfo { "window/showMessageRequest", true, MessageDirection::server_to_client, "window.showMessage", "" },
    MethodInfo { "window/workDoneProgress/cancel", false, MessageDirection::client_to_server, "", "" },
    MethodInfo { "window/workDoneProgress/create", true, MessageDirection::server_to_client, "window.workDoneProgress", "" },
    MethodInfo { "workspace/applyEdit", true, MessageDirection::server_to_client, "workspace.applyEdit", "" },
    MethodInfo { "workspace/codeLens/refresh", true, MessageDirection::server_to_client, "workspace.codeLens", "" },
    MethodInfo { "workspace/configuration", true, MessageDirection::server_to_client, "workspace.configuration", "" },
    MethodInfo { "workspace/diagnostic", true, MessageDirection::client_to_server, "workspace.diagnostics", "diagnosticProvider.workspaceDiagnostics" },
    MethodInfo { "workspace/diagnostic/refresh", true, MessageDirection::server_to_client, "workspace.diagnostics.refreshSupport", "" },
    MethodInfo { "workspace/didChangeConfiguration", false, MessageDirection::client_to_server, "workspace.didChangeConfiguration", "" },
    MethodInfo { "workspace/didChangeWatchedFiles", false, MessageDirection::client_to_server, "workspace.didChangeWatchedFiles", "" },
    MethodInfo { "workspace/didChangeWorkspaceFolders", false, MessageDirection::client_to_server, "", "workspace.workspaceFolders.changeNotifications" },
    MethodInfo { "workspace/didCreateFiles", false, MessageDirection::client_to_server, "workspace.fileOperations.didCreate", "workspace.fileOperations.didCreate" },
    MethodInfo { "workspace/didDeleteFiles", false, MessageDirection::client_to_server, "workspace.fileOperations.didDelete", "workspace.fileOperations.didDelete" },
    MethodInfo { "workspace/didRenameFiles", false, MessageDirection::client_to_server, "workspace.fileOperations.didRename", "workspace.fileOperations.didRename" },
    MethodInfo { "workspace/executeCommand", true, MessageDirection::client_to_server, "workspace.executeCommand", "executeCommandProvider" },
    MethodInfo { "workspace/foldingRange/refresh", true, MessageDirection::server_to_client, "workspace.foldingRange.refreshSupport", "" },
    MethodInfo { "workspace/inlayHint/refresh", true, MessageDirection::server_to_client, "workspace.inlayHint.refreshSupport", "" },
    MethodInfo { "workspace/inlineValue/refresh", true, MessageDirection::server_to_client, "workspace.inlineValue.refreshSupport", "" },
    MethodInfo { "workspace/semanticTokens/refresh", true, MessageDirection::server_to_client, "workspace.semanticTokens.refreshSupport", "" },
    MethodInfo { "workspace/symbol", true, MessageDirection::client_to_server, "workspace.symbol", "workspaceSymbolProvider" },
    MethodInfo { "workspace/textDocumentContent", true, MessageDirection::client_to_server, "workspace.textDocumentContent", "workspace.textDocumentContent" },
    MethodInfo { "workspace/textDocumentContent/refresh", true, MessageDirection::server_to_client, "", "" },
    MethodInfo { "workspace/willCreateFiles", true, MessageDirection::client_to_server, "workspace.fileOperations.willCreate", "workspace.fileOperations.willCreate" },
    MethodInfo { "workspace/willDeleteFiles", true, MessageDirection::client_to_server, "workspace.fileOperations.willDelete", "workspace.fileOperations.willDelete" },
    MethodInfo { "workspace/willRenameFiles", true, MessageDirection::client_to_server, "workspace.fileOperations.willRename", "workspace.fileOperations.willRename" },
    MethodInfo { "workspace/workspaceFolders", true, MessageDirection::server_to_client, "workspace.workspaceFolders", "workspace.workspaceFolders" },
    MethodInfo { "workspaceSymbol/resolve", true, MessageDirection::client_to_server, "workspace.symbol.resolveSupport", "workspaceSymbolProvider.resolveProvider" },
} };

} // namespace

std::span<const MethodInfo> methods() { return METHODS; }

const MethodInfo* find_method(std::string_view name) {
    const auto it = std::ranges::lower_bound(METHODS, name, {}, &MethodInfo::name);
    if (it == METHODS.end() || it->name != name) return nullptr;
    return &*it;
}

} // namespace mcppls::lsp
